### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by hanbim520** [UbbeLoL/Native-QuasarClient#1]
hi, i'm writing c++ passwordlibrary .Now i have finished ie and chrome and wifi password code  which saved on windows .

**Comment by UbbeLoL** [comment]
You can submit it in a pull request if you wish, but I might hold off to implement arguably superfluous features like password recovery until I got a stable core.

**Comment by hanbim520** [comment]
https://github.com/hanbim520/PasswordLibrary.git     
Now it's empty,this saturday i'll push the project. The project also use cmake.I just want to learn knowledge of cryptography. My english is not good.

**Comment by UbbeLoL** [comment]
I'll check it out when you push it. For the protobuf part, are you talking about the packets in Native-QuasarClient or your password library?

**Comment by hanbim520** [comment]
QuasarClient  if u want to run in different operating systems,system will have the size of the end of the problem.google-protobuf will be a good solution。Password library only works on local computer now.

**Comment by dummy0stud** [comment]
hi guys, you have plans to add remote desktop anytime soon?

**Comment by UbbeLoL** [comment]
@hanbim520 The packet format is based on the QuasarServer format, and the serialization is based on [NetSerializer](https://github.com/tomba/netserializer) in order to make it compatible. This works on multiple operating systems including Windows, various Linux distributions and OS X.

**Comment by UbbeLoL** [comment]
@dummy0stud Please open a separate issue if you want to discuss features.

**Comment by Pandry** [comment]
Nice!
