### ISSUE TITLE
Remote desktop priority

### ISSUE THREAD

**Issue by dummy0stud** [UbbeLoL/Native-QuasarClient#3]
Where is remote desktop in your todo list? Have you decided the protocol?(vnc, rpc) grpc looks good for multiplexing but I am not sure if it is designed for video streaming

**Comment by UbbeLoL** [comment]
It's in the list. The Quasar server uses [UnsafeStreamCodec ](https://github.com/AnguisCaptor/StreamLibrary/blob/master/StreamLibrary/UnsafeCodecs/UnsafeStreamCodec.cs) so I will have to match that in the client. I am however planning on doing my own implementation of the encoding part.

**Comment by Pandry** [comment]
I think that a remote shell would be more important
