### ISSUE TITLE
How to use Native-QuasarClient with Quasar?

### ISSUE THREAD

**Issue by Pouya47** [ubbelol/Native-QuasarClient#5]
Hi
I compiled Native-QuasarClient on linux, but  I get a bit confused, How I can use Native-QuasarClient with Quasar to build native client?

**Comment by ubbelol** [comment]
The native client cannot be built from the regular Quasar software. You need to compile it manually and put in your remote address and port in the settings: https://github.com/ubbelol/Native-QuasarClient/blob/c7582d970dd040e8bab57793a7fe725634ba7616/include/settings.h#L4
